version: "3.8"
services:
  synapse:
    image: matrixdotorg/synapse
    ports:
      - "8008:8008"
    volumes:
      - ./data:/data
    environment:
      - SYNAPSE_SERVER_NAME=matrix.easypi.duckdns.org
      - SYNAPSE_HTTP_PORT=8008
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_DATA_DIR=/data
      - SYNAPSE_CONFIG_DIR=/data
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=991
      - GID=991
      - TZ=UTC
    restart: unless-stopped
