version: "3.8"
services:
  sniproxy:
    image: vimagick/sniproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/etc:/etc/sniproxy
      - ./data/log:/var/log/sniproxy
    restart: unless-stopped
