version: "3.8"

services:
  elastalert:
    image: jertel/elastalert2
    volumes:
      - ./data/config.yaml:/opt/elastalert/config.yaml
      - ./data/rules:/opt/elastalert/rules
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

networks:
  default:
    external:
      name: elk_default
