version: "3.8"
services:
  gladys:
    image: gladysassistant/gladys:v4
    volumes:
      - ./data:/var/lib/gladysassistant
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - NODE_ENV=production
      - SERVER_PORT=80
      - TZ=UTC
      - SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    network_mode: host
    privileged: true
    restart: unless-stopped
